name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      # run tests on all versions, even if one fails
      fail-fast: false
      matrix:
        # add any other Typst versions that your package should support
        typst-version:
          - typst: "0.13.1"
            tytanic: "0.2"

    name: Test for ${{ matrix.typst-version.typst }} (Tytanic ${{ matrix.typst-version.tytanic }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install just and tytanic
        uses: taiki-e/install-action@v2
        with:
          tool: just,tytanic@${{ matrix.typst-version.tytanic }}

      - name: Setup typst
        id: setup-typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: ${{ matrix.typst-version.typst }}

      - name: Setup Package
        run: just install-preview

      - name: Run test suite
        run: |
          just test

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: typst-${{ steps.setup-typst.outputs.typst-version }}-test-results
          path: |
            tests/**/diff/*.png
            tests/**/out/*.png
            tests/**/ref/*.png
          retention-days: 5
